### ISSUE TITLE
Add a link to github on homepage?

### ISSUE THREAD

**Issue by jfly** [jonatanklosko/wca_statistics#1]
When I go to https://jonatanklosko.github.io/wca_statistics/, there's no evidence that the code is open sourced on github, other than if I'm smart enough to know how to find the repository behind a `*.github.io` url.

It would also be cool if individual stats (such as https://jonatanklosko.github.io/wca_statistics/best_result_off_podium) could link directly to their source code. I think that could motivate curious people to investigate and maybe send in PRs with their own stats!

**Comment by jfly** [comment]
@jonatanklosko, if you're open to any of this, I'm happy to dive in and try to send in a PR =)

**Comment by jonatanklosko** [comment]
Fixed in 06f3545bab502b9da3cd34af96a78a2e7676fb6f! I decided to go for a single link to the repo as per our discussion offline.
