### ISSUE TITLE
[Suggestion] Longest currently active PR streak

### ISSUE THREAD

**Issue by JustinTimeCuber** [jonatanklosko/wca_statistics#10]
Same as the "[Longest streak of competitions with a personal record done](https://jonatanklosko.github.io/wca_statistics/longest_streak_of_personal_records)" ranking, but only including ongoing streaks.

**Comment by jonatanklosko** [comment]
Hey @JustinTimeCuber! I'd rather avoid duplicated statistics like that. If there's a specific reason you're interested in this, you can try computing it locally and change [this line](https://github.com/jonatanklosko/wca_statistics/blob/49618b7df8f8312f0103c1978c294e02a00b01b3/statistics/longest_streak_of_personal_records.rb#L55) to include more entries (or filter accordingly) :)
