### ISSUE TITLE
worst_result_on_podium not counting singles in ao5/mo3 events.

### ISSUE THREAD

**Issue by toadfrommariokart64** [jonatanklosko/wca_statistics#12]
in [worst_result_on_podium](https://github.com/jonatanklosko/wca_statistics/blob/master/statistics/worst_result_on_podium.rb) you're disregarding results that podiumed with a DNF mean in rounds where the format is ao5/mo3.

**Comment by toadfrommariokart64** [comment]
7x7 is wrong for example, as it's missing the 13:29 single (DNF mean) from this podium: https://www.worldcubeassociation.org/competitions/BrasiliaOpen2009/results/podiums#e777

**Comment by jonatanklosko** [comment]
This is expected. If we count those cases, then all rankings become by-single and it is much less interesting in my opinion. I added a clarification in 41d7e049da4bc584dd4a007bbe72b39b74e9bf99.
