### ISSUE TITLE
longest_streak_of_competitions_in_own_country not working

### ISSUE THREAD

**Issue by JustinTimeCuber** [jonatanklosko/wca_statistics#13]
I don't think [this](https://jonatanklosko.github.io/wca_statistics/longest_streak_of_competitions_in_own_country) does what it's supposed to do:
![image](https://user-images.githubusercontent.com/46458276/231360556-bec5ded8-efa2-491e-a096-8b635e1be3a4.png)
[Niko Ronkainen](https://www.worldcubeassociation.org/persons/2010RONK01?tab=map)
![image](https://user-images.githubusercontent.com/46458276/231360844-0f41ca8b-d0af-4164-9533-10f23e760ca2.png)
[Daniel Vædele Egdal](https://www.worldcubeassociation.org/persons/2013EGDA01?tab=map)
![image](https://user-images.githubusercontent.com/46458276/231360921-12eba809-eac8-4816-877d-9d723580518f.png)

**Comment by jonatanklosko** [comment]
Hey @JustinTimeCuber, the streak doesn't end when they participate abroad, but when they miss a competition happening in their country :)

> Note: The streak ends whenever the person doesn’t participate in a competition in own country.

**Comment by JustinTimeCuber** [comment]
Ah, okay. I was misreading that note.
