### ISSUE TITLE
Suggestion for Improvement in Rolling Average page

### ISSUE THREAD

**Issue by onionhoney** [jonatanklosko/wca_statistics#4]
Since 2x2 singles is a very random event, many world-level speedcubers are excluded from the average list, which I believe renders the list very misrepresentative. For example, the current WR3, Jiazhou Li, completely vanishes from all 2x2 rolling average rankings. Can you fix this? e.g. you can filter by top 100 official average instead for events with chance singles.

**Comment by jonatanklosko** [comment]
Actually, Jiazhou Li is on the list (currently 9th):
![image](https://user-images.githubusercontent.com/17034772/74100753-6c8f4c80-4b32-11ea-9e1c-0b10ac07b781.png)

Being a random event doesn't really matter here, as the average tries to imitate the recent trend:
![image](https://user-images.githubusercontent.com/17034772/74100778-b0825180-4b32-11ea-85e1-8b0a845390e2.png)

The idea behind this ranking is to show people who's been doing relatively great recently and it's perfectly fine if someone with great personal best, but bad recent results doesn't show up on the list.

It's easy to include more people, but I think top 50 is definitely enough.

**Comment by onionhoney** [comment]
Sorry I was unclear about what page I was referring to. 
It's the historically best consecutive average pages, not the current average. Like these ones: https://jonatanklosko.github.io/wca_statistics/average_of_5 

For the page you were discussing, I think that's perfectly fine. But that was not the page or the issue I was referring to -- I was talking about the method of filtering by the best overall single result, for the consecutive average pages.
 
If you can take a look at this again? Thank you.

**Comment by jonatanklosko** [comment]
Ah sorry, I totally didn't get what you pointed out! I agree that the heuristic of considering top 100 single competitors failed in this case. I didn't use average as for some events (especially BLD) it may also ignore good competitors, so for now I'll just update it to consider top 200 single ^^
