### ISSUE TITLE
Some rankings cannot be shown (because of 333ft deletion?)

### ISSUE THREAD

**Issue by sakabar** [jonatanklosko/wca_statistics#5]
Hi. I found some rankings cannot be shown.

https://jonatanklosko.github.io/wca_statistics/shortest_time_to_get_all_singles
https://jonatanklosko.github.io/wca_statistics/shortest_time_to_get_all_singles_and_averages

I wonder this is caused by deletion of 333ft.

**Comment by jonatanklosko** [comment]
Good point, I've just updated the list of official events, so it should fix all the related stats, thanks! (stats will be updated once the build finishes).
