### ISSUE TITLE
Delegated competitions per year is not fully correct

### ISSUE THREAD

**Issue by AlexKatyukov** [jonatanklosko/wca_statistics#6]
For example Anton Rostovikov is not Delegate for ~5 years but his time is foing on. His years is 8.29 but ~3 will be more correct.

**Comment by jonatanklosko** [comment]
We don't really know the exact dates for delegates, as we do for team members. I've updated it to consider delegation period as the difference between first and last competition, which should lead to more reasonable results. Delegates who quickly delegate several competitions and then become idle will show up high in the ranking, but I'd say there's not much more we can do with the current data.
