### ISSUE TITLE
The "Most delegated competitions" stat includes cancelled competitions

### ISSUE THREAD

**Issue by viroulep** [jonatanklosko/wca_statistics#8]
It seems that the statistic currently includes competitions that were cancelled, which technically were never actually delegated.

I would assume it's just a matter of adding a check on `cancelled_at` [here](https://github.com/jonatanklosko/wca_statistics/blob/master/statistics/most_delegated_competitions.rb#L21)? (and [here too](https://github.com/jonatanklosko/wca_statistics/blob/master/statistics/delegated_competition_per_year.rb#L26) I guess)

**Comment by jonatanklosko** [comment]
Fixed in d85d2b1e66c845bd767118eb7bd8f84560bfc356, thanks!
