### ISSUE TITLE
"Most BLD attempts before succes" not working correctly

### ISSUE THREAD

**Issue by toadfrommariokart64** [jonatanklosko/wca_statistics#9]
2017JARN01 should appear under 3BLD as having done 37 attempts before getting a succes

**Comment by toadfrommariokart64** [comment]
just a misunderstanding of when the data was from, sorry. see Daniel's post https://github.com/jonatanklosko/wca_statistics/issues/11 for a suggestion on how to make this more clear

**Comment by jonatanklosko** [comment]
Hey @carlemilex! The stats are computed daily, but rely on (a) results being posted and (b) the WCA export being updated. The idea in #11 sounds good!
